####################### Project: Test Code ########################
##### Description: 
##### 1. Test function for each auxiliary function 
##### 2. Three test functions for the select() function 
#####    ( testStepwise(), testSim1() & testSim2() ) 
###################################################################
test <- function(){
  testInitial()
  cat("\n")
  testSingleEval()
  cat("\n")
  testEval()
  cat("\n")
  testUpdate()
  cat("\n")
  testCrossOver()
  cat("\n")
  testMutation()
  cat("\n")
  testStepwise()
  cat("\n")
  testSim1()
  cat("\n")
  testSim2()
}

testInitial <- function(){
  pop <- popInitialize(popSize = 100, zeroToOneRatio = 1, geneLength = 10)
  cat("1. The popInitialize() function returns an initial generation of models with 1 indicating an included variable and 0 indicating an excluded variable.\n")
  cat("Here is what one model inside the generation looks like :\n")
  print(pop[1,])
  cat("The zero-to-one ratio in the model is approximately 1 to 1 as specified in default.\n")
}

testSingleEval <- function(){
  
  X <- mtcars[,2:11]
  y <- mtcars[,1]
  singleGene <- sample(c(0,1),dim(X)[2],replace=T)
  criValue <- singleEval(singleGene,X,y,"lm","BIC",NULL,"gaussian")
  cat("2. The singleEval() function returns the value of the evaluation criterion for one specified model.\n")
  cat("For example, the BIC here is:\n")
  cat(criValue)
  cat("\n")
}

testEval <- function(){
  X <- mtcars[,2:11]
  y <- mtcars[,1]
  currentGenePool <- popInitialize(popSize = 100, geneLength = dim(X)[2],zeroToOneRatio = 1)
  criterion <- evalFunction(X,y,currentGenePool = currentGenePool,popSize = 100)
  cat("3. The evalFunction() returns the AIC rank and sampling probability of each of the models in the generation, for example:\n")
  print(criterion[,1])
  cat("\n")
}

testUpdate <- function(){
  weights <-rep(1,100)
  currentGenePool <- popInitialize(popSize = 100, geneLength = dim(X)[2],zeroToOneRatio = 1)
  newGenePool <- updateSamp(currentGenePool,popSize = 100, weights = weights)
  cat("4. The updateSamp function updates the population according to the specified weights.\n")
  cat("Here is what one model in the new generation looks like:\n")
  print(newGenePool[1,])
}

testCrossOver <- function(){
  v1 <- rep(1,10)
  v2 <- rep(0,10)
  geneLength <- length(v1)
  child <- crossover(v1,v2,geneLength,1)
  cat("5. The crossover() function returns two models generated by cross over:\n")
  cat("The genes before crossover:\n")
  print(rbind(v1,v2))
  cat("The genes after crossover:\n")
  print(child)
  cat("\n")
  
}

testMutation <- function(){
  v1 <- sample(c(0,1),10,replace=T)
  v2 <- sample(c(1,0),10,replace=T)
  geneLength <- length(v1)
  child <- mutation(v1,v2,1)
  
  cat("6. The mutation() function returns two models generated from mutation:\n")
  cat("The genes before mutation:\n")
  print(rbind(v1,v2))
  cat("The genes after mutation:\n")
  print(child)
  cat("\n")
  
}

testBest <- function(){
  X <- mtcars[,2:11]
  y <- mtcars[,1]
  currentPool <- popInitialize(popSize = 100, geneLength = dim(mtcars)[2],zeroToOneRatio = 1)
  best(X = X, y = y, pool = currentPool, popSize = 100, type = "lm", criterion = "AIC")
}

testStepwise = function(){
  ##### Implement our function on the mtcars dataset ###### 
  ##### Using stepwise regression on the same dataset and compare the results #####
  X <- mtcars[,2:11]
  y <- mtcars[,1]
  
  cat("Testing select() function on mtcars dataset ... \n")
  cat("Our function running ...")
  set.seed(1)
  result <- select(X, y, popSize = 100, max_iterations = 500, crossRate = 0.95, mRate = 0.0001)
  cat("Now we implement stepwise regression on the dataset.")
  fullModel <- lm( mpg ~ cyl+disp+hp+drat+wt+qsec+vs+am+gear+carb, data = mtcars)
  stepResult <- step(fullModel, direction = "both", trace = 1)
  cat("The stepwise regression has picked the following model:")
  print(summary(stepResult))
  cat("The AIC value for this model is:",AIC(stepResult),"\n")
  cat("\n")
  cat("Our function has chosen the following model:")
  print(summary(result))
  cat("The AIC value for our model is:",unlist(AIC(result)),"\n")
  cat("\n")
  
  if((abs(AIC(result)-AIC(stepResult))) < 10)
    cat("The model our function chose is close to the one that stepwise regression chose. Test succeeded.\n")
  else
    cat("The model our function chose is not close to the one that stepwise regression chose. Test failed.\n")
}



testSim1 <- function(){
##### Simulate outcome variable based on 5 predicting variables #####
##### Throw in 6 more "noise" variables and use our function to select the predictor variables #####
X <- mtcars[,1:11]
n <- dim(mtcars)[1]
error <- matrix(rnorm(n),nrow = n)
y <- 1*X[,1] + 2*X[,2] + 3*X[,3] + 4*X[,4] + 5*X[,5] + error

cat("Testing our function on the simulated dataset ...\n")
cat("Our function running ...\n")
set.seed(1)
result <- select (X, y, popSize = 200, max_iteration = 200, criterion = "AIC", zeroToOneRatio = 1, crossRate = 0.95, mRate = 0.001)
cat("Our function has chosen the following model:")
print(summary(result))
cat("The AIC value for our model is:",unlist(AIC(result)),"\n")
cat("The true model has the mpg, cyl, disp, hp and drat as the independent variables.\n")
cat("Using the current seed, our function has picked out all of the 5 relevant variables but included 1 additional irrelevant variable. The performance of our function is decent. Test succeeded.")
}

testSim2 <- function(){
##### Simulate outcome variable based on 5 predicting variables #####
##### Throw in 36 more "noise" variables and use our function to select the predictor variables #####
  X1 <- mtcars[,1:11]
  n <- dim(mtcars)[1]
  X2 <- matrix(sample(0:100,30*n,replace = T),nrow = n)
  X <- cbind(X1,X2)
  error <- matrix(rnorm(n),nrow = n)
  y <- 1*X[,1] + 2*X[,2] + 3*X[,3] + 4*X[,4] + 5*X[,5] + error
  
  cat("Testing our function on the simulated dataset ...\n")
  cat("Our function running ...\n")
  set.seed(1)
  result <- select (X, y, popSize = 300, max_iteration = 200, criterion = "AIC", zeroToOneRatio = 5, crossRate = 0.95, mRate = 0.001)
  cat("Our function has chosen the following model:")
  print(summary(result))
  cat("The AIC value for our model is:",unlist(AIC(result)),"\n")
  cat("The true model has the mpg, cyl, disp, hp and drat as the independent variables.\n")
  cat("Using the current seed, our function has picked out all of the 5 relevant variables but included 1 additional irrelevant variable. The performance of our function is decent. Test succeeded.")
  
  
}



